[build]
  command = "npm run build"
  publish = "dist/g-int"
  environment = { NETLIFY_USE_YARN = "false" }

# Redirect root to /G-int/
[[redirects]]
  from = "/"
  to = "/G-int/"
  status = 301

# Handle assets with correct path prefix
[[redirects]]
  from = "/G-int/*"
  to = "/:splat"
  status = 200


# Handle all other routes with Angular's router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
